class BaseIndexerException(BaseException): ...


class IndexerDatabaseError(BaseIndexerException): ...


class IndexerSettingsError(BaseIndexerException): ...


class TonApiError(BaseIndexerException): ...
