//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::account_last_trace::Entity as AccountLastTrace;
pub use super::dao::Entity as Dao;
pub use super::proposal::Entity as Proposal;
